kind: Deployment
apiVersion: apps/v1
metadata:
  name: graph-ms
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-ms 
  template:
    metadata:
      labels:
        app:  graph-ms 
    spec:
      containers:
        - name: graph-ms 
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: graph-ms 
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: graph-ms 
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: graph-ms 
  namespace: prod
spec:
  rules:
  - host: graphing.jodios.com
    http:
      paths:
      - backend:
          serviceName: graph-ms 
          servicePort: 5000